package runtime

import (
	"agent-runtime/internal/llm"
	"agent-runtime/internal/model"
	"context"
	"strings"
	"testing"
)

// TestLLMPlanner_ParsesPlanJSON Stub 返回合法计划 JSON，应解析为对应 Plan。
func TestLLMPlanner_ParsesPlanJSON(t *testing.T) {
	planJSON := `{"nodes":[
		{"id":"n1","type":"TOOL","name":"search","input":"go agent","dependsOn":[]},
		{"id":"n2","type":"LLM","name":"reason","input":"summarize","dependsOn":["n1"]}
	]}`
	stub := &llm.Stub{Responder: func(_ llm.Request) string { return planJSON }}
	p, err := (&LLMPlanner{LLM: stub}).Plan(context.Background(), &model.Run{ID: "run-1", Input: "research go agents"})
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if len(p.Nodes) != 2 {
		t.Fatalf("expected 2 nodes, got %d", len(p.Nodes))
	}
	if p.Nodes[0].Type != model.NodeTool || p.Nodes[0].Name != "search" {
		t.Errorf("node0 = %+v", p.Nodes[0])
	}
	if len(p.Nodes[1].DependsOn) != 1 || p.Nodes[1].DependsOn[0] != "run-1:n1" {
		t.Errorf("node1 deps = %+v", p.Nodes[1].DependsOn)
	}
}

// TestLLMPlanner_StripsMarkdownFence Stub 返回带 ```json 围栏的 JSON，应仍能解析。
func TestLLMPlanner_StripsMarkdownFence(t *testing.T) {
	wrapped := "```json\n" + `{"nodes":[{"id":"x","type":"LLM","name":"gen","input":"hi","dependsOn":[]}]}` + "\n```"
	stub := &llm.Stub{Responder: func(_ llm.Request) string { return wrapped }}
	p, err := (&LLMPlanner{LLM: stub}).Plan(context.Background(), &model.Run{ID: "r", Input: "g"})
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if len(p.Nodes) != 1 || p.Nodes[0].ID != "r:x" {
		t.Errorf("unexpected plan: %+v", p)
	}
}

// TestLLMPlanner_InvalidJSON_ReturnsError 非法 JSON 应报错而非返回空计划。
func TestLLMPlanner_InvalidJSON_ReturnsError(t *testing.T) {
	stub := &llm.Stub{Responder: func(_ llm.Request) string { return "this is not json" }}
	_, err := (&LLMPlanner{LLM: stub}).Plan(context.Background(), &model.Run{ID: "r", Input: "g"})
	if err == nil || !strings.Contains(err.Error(), "parse plan json") {
		t.Fatalf("expected parse error, got %v", err)
	}
}

// TestLLMPlanner_EmptyPlan_ReturnsError 空计划应报错。
func TestLLMPlanner_EmptyPlan_ReturnsError(t *testing.T) {
	stub := &llm.Stub{Responder: func(_ llm.Request) string { return `{"nodes":[]}` }}
	_, err := (&LLMPlanner{LLM: stub}).Plan(context.Background(), &model.Run{ID: "r", Input: "g"})
	if err == nil || !strings.Contains(err.Error(), "empty") {
		t.Fatalf("expected empty-plan error, got %v", err)
	}
}

// TestLLMPlanner_MissingID_AutoGenerated 缺省 ID 的节点应自动生成兜底 ID。
func TestLLMPlanner_MissingID_AutoGenerated(t *testing.T) {
	stub := &llm.Stub{Responder: func(_ llm.Request) string {
		return `{"nodes":[{"type":"LLM","name":"gen","input":"hi","dependsOn":[]}]}`
	}}
	p, err := (&LLMPlanner{LLM: stub}).Plan(context.Background(), &model.Run{ID: "run-9", Input: "g"})
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if p.Nodes[0].ID == "" {
		t.Error("expected auto-generated ID for missing id")
	}
	if !strings.HasPrefix(p.Nodes[0].ID, "run-9:") {
		t.Errorf("auto ID should be prefixed by run id, got %q", p.Nodes[0].ID)
	}
}

// TestLLMPlanner_NilClient_Errors 未配置客户端应显式报错。
func TestLLMPlanner_NilClient_Errors(t *testing.T) {
	_, err := (&LLMPlanner{}).Plan(context.Background(), &model.Run{ID: "r", Input: "g"})
	if err == nil || !strings.Contains(err.Error(), "not configured") {
		t.Fatalf("expected not-configured error, got %v", err)
	}
}

// TestLLMPlanner_LLMError_Propagates LLM 调用错误应传播。
func TestLLMPlanner_LLMError_Propagates(t *testing.T) {
	stub := &llm.Stub{}
	// 通过已取消的 ctx 触发 LLM 错误。
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	_, err := (&LLMPlanner{LLM: stub}).Plan(ctx, &model.Run{ID: "r", Input: "g"})
	if err == nil {
		t.Fatal("expected error from cancelled context")
	}
}

// TestValidatePlan_Cycle 含环的 DAG 应报错。
func TestValidatePlan_Cycle(t *testing.T) {
	plan := model.Plan{Nodes: []model.PlanNode{
		{ID: "a", Type: model.NodeLLM, DependsOn: []string{"b"}},
		{ID: "b", Type: model.NodeLLM, DependsOn: []string{"a"}},
	}}
	if err := validatePlan(plan); err == nil || !strings.Contains(err.Error(), "cycle") {
		t.Fatalf("expected cycle error, got %v", err)
	}
}

// TestValidatePlan_DanglingDep 依赖不存在节点应报错。
func TestValidatePlan_DanglingDep(t *testing.T) {
	plan := model.Plan{Nodes: []model.PlanNode{
		{ID: "a", Type: model.NodeLLM, DependsOn: []string{"missing"}},
	}}
	if err := validatePlan(plan); err == nil || !strings.Contains(err.Error(), "unknown node") {
		t.Fatalf("expected dangling-dep error, got %v", err)
	}
}

// TestValidatePlan_DuplicateID 重复 ID 应报错。
func TestValidatePlan_DuplicateID(t *testing.T) {
	plan := model.Plan{Nodes: []model.PlanNode{
		{ID: "a", Type: model.NodeLLM},
		{ID: "a", Type: model.NodeLLM},
	}}
	if err := validatePlan(plan); err == nil || !strings.Contains(err.Error(), "duplicate") {
		t.Fatalf("expected duplicate error, got %v", err)
	}
}

// TestNamespacePlan_PrefixesAndUpdatesRefs 命名空间化应加前缀并更新引用。
func TestNamespacePlan_PrefixesAndUpdatesRefs(t *testing.T) {
	plan := model.Plan{Nodes: []model.PlanNode{
		{ID: "n1", Type: model.NodeTool, DependsOn: nil},
		{ID: "n2", Type: model.NodeLLM, DependsOn: []string{"n1"}, ParentNodeID: "n1"},
	}}
	namespacePlan(&plan, "run-1")
	if plan.Nodes[0].ID != "run-1:n1" {
		t.Errorf("node0 ID = %q, want run-1:n1", plan.Nodes[0].ID)
	}
	if plan.Nodes[1].ID != "run-1:n2" {
		t.Errorf("node1 ID = %q, want run-1:n2", plan.Nodes[1].ID)
	}
	if plan.Nodes[1].DependsOn[0] != "run-1:n1" {
		t.Errorf("dependsOn = %v, want [run-1:n1]", plan.Nodes[1].DependsOn)
	}
	if plan.Nodes[1].ParentNodeID != "run-1:n1" {
		t.Errorf("parent = %q, want run-1:n1", plan.Nodes[1].ParentNodeID)
	}
}
